In [1]:
import glob
 
# list all csv files only
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['google.csv', 'tripadvisor.csv']

In [2]:
import pandas as pd
 
l = []
 
for f in csv_files:
    l.append(pd.read_csv(f))
     
df_res = pd.concat(l, ignore_index=True)
df_res

,name,rating,review,language,review_date,platform
0,Trung Diep,5,If you love Poke bowls this is the place! 10/1...,en,2022-07-20,google
1,Ibrahim Sheikh,5,An unbelievable poke bowl for the cost. The in...,en,2022-05-21,google
2,Caitlin McMenamin,5,Fresh and delicious food! I came at lunchtime ...,en,2022-10-18,google
3,Nhung Nguyen,4,Very fresh bowl with colorful. The price is 18...,en,2022-06-20,google
4,Ruby Schlaker,5,Some of the most delicious poke I have ever ha...,en,2023-03-17,google
...,...,...,...,...,...,...
1740,GNS589,5,We read reviews for Poke Saigon and tried it f...,en,2018-01-01,tripadvisor
1741,aaronchiang,5,Back in Saigon and had to come to Poke Saigon....,en,2018-01-01,tripadvisor
1742,Djrick_08,5,"A nice little spot, the freshest salmon with a...",en,2018-01-01,tripadvisor
1743,pamelie,5,With its tropicool atmosphere and healthy yet ...,en,2018-01-01,tripadvisor
1744,anniep297,5,Wow! The food is so fresh and fulfilling! You ...,en,2017-12-01,tripadvisor

In [3]:
df_res.to_csv('output/feedback.csv', index=False)